// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\FFT.v
// Created: 2026-07-16 10:54:42
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT
// Source Path: fft8/fft8_dut/FFT
// Hierarchy Level: 1
// Model version: 1.11
// 
// FFT
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // int16
  input   validIn;
  output  signed [18:0] dataOut_re;  // sfix19
  output  signed [18:0] dataOut_im;  // sfix19
  output  validOut;


  wire signed [15:0] dtc_re;  // sfix16
  reg signed [15:0] intdelay_reg [0:2];  // sfix16 [3]
  reg signed [15:0] intdelay_reg_next [0:2];  // sfix16 [3]
  reg signed [15:0] din_1_1_re_dly;  // sfix16
  wire signed [15:0] dtc_im;  // sfix16
  reg signed [15:0] intdelay_reg_1 [0:2];  // sfix16 [3]
  reg signed [15:0] intdelay_reg_next_1 [0:2];  // sfix16 [3]
  reg signed [15:0] din_1_1_im_dly;  // sfix16
  reg  [2:0] intdelay_reg_2;  // ufix1 [3]
  wire din_1_vld_dly;
  wire dinXTwdl_1_1_vld;
  wire [1:0] rd_1_Addr;  // ufix2
  wire rd_1_Enb;
  wire proc_1_enb;
  wire signed [16:0] dout_1_1_re;  // sfix17
  wire signed [16:0] dout_1_1_im;  // sfix17
  wire dout_1_1_vld;
  wire dinXTwdl_2_1_vld;
  wire rd_2_Addr;  // ufix1
  wire rd_2_Enb;
  wire proc_2_enb;
  wire multiply_2_J;
  wire signed [17:0] dout_2_1_re;  // sfix18
  wire signed [17:0] dout_2_1_im;  // sfix18
  wire dout_2_1_vld;
  reg signed [17:0] intdelay_reg_3 [0:2];  // sfix18 [3]
  reg signed [17:0] intdelay_reg_next_2 [0:2];  // sfix18 [3]
  reg signed [17:0] din_3_re_dly;  // sfix18
  reg signed [17:0] intdelay_reg_4 [0:2];  // sfix18 [3]
  reg signed [17:0] intdelay_reg_next_3 [0:2];  // sfix18 [3]
  reg signed [17:0] din_3_im_dly;  // sfix18
  reg  [2:0] intdelay_reg_5;  // ufix1 [3]
  wire din_3_vld_dly;
  wire signed [15:0] twdl_3_re;  // sfix16_En14
  wire signed [15:0] twdl_3_im;  // sfix16_En14
  wire rd_3_Enb;
  reg  rd_3_Enb_dly;
  wire dinXTwdl_3_vld;
  wire rd_3_Addr;
  wire proc_3_enb;
  wire signed [18:0] dout_3_re;  // sfix19
  wire signed [18:0] dout_3_im;  // sfix19
  wire dout_3_vld;
  wire signed [18:0] dout_re1;  // sfix19
  wire signed [18:0] dout_im1;  // sfix19
  wire dout_vld1;
  reg signed [31:0] intdelay_t_0_0;  // int32
  reg signed [31:0] intdelay_t_0_1;  // int32
  reg signed [31:0] intdelay_t_1;  // int32
  reg signed [31:0] intdelay_t_0_0_1;  // int32
  reg signed [31:0] intdelay_t_0_1_1;  // int32
  reg signed [31:0] intdelay_t_1_1;  // int32
  reg signed [31:0] intdelay_t_0_0_2;  // int32
  reg signed [31:0] intdelay_t_0_1_2;  // int32
  reg signed [31:0] intdelay_t_1_2;  // int32
  reg signed [31:0] intdelay_t_0_0_3;  // int32
  reg signed [31:0] intdelay_t_0_1_3;  // int32
  reg signed [31:0] intdelay_t_1_3;  // int32


  assign dtc_re = dataIn;

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd2; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg[intdelay_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd2; intdelay_t_0_1 = intdelay_t_0_1 + 32'sd1) begin
            intdelay_reg[intdelay_t_0_1] <= intdelay_reg_next[intdelay_t_0_1];
          end
        end
      end
    end

  always @* begin
    din_1_1_re_dly = intdelay_reg[2];
    intdelay_reg_next[0] = dtc_re;

    for(intdelay_t_0_0 = 32'sd0; intdelay_t_0_0 <= 32'sd1; intdelay_t_0_0 = intdelay_t_0_0 + 32'sd1) begin
      intdelay_reg_next[intdelay_t_0_0 + 32'sd1] = intdelay_reg[intdelay_t_0_0];
    end

  end

  assign dtc_im = 16'sb0000000000000000;

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_1 = 32'sd0; intdelay_t_1_1 <= 32'sd2; intdelay_t_1_1 = intdelay_t_1_1 + 32'sd1) begin
          intdelay_reg_1[intdelay_t_1_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(intdelay_t_0_1_1 = 32'sd0; intdelay_t_0_1_1 <= 32'sd2; intdelay_t_0_1_1 = intdelay_t_0_1_1 + 32'sd1) begin
            intdelay_reg_1[intdelay_t_0_1_1] <= intdelay_reg_next_1[intdelay_t_0_1_1];
          end
        end
      end
    end

  always @* begin
    din_1_1_im_dly = intdelay_reg_1[2];
    intdelay_reg_next_1[0] = dtc_im;

    for(intdelay_t_0_0_1 = 32'sd0; intdelay_t_0_0_1 <= 32'sd1; intdelay_t_0_0_1 = intdelay_t_0_0_1 + 32'sd1) begin
      intdelay_reg_next_1[intdelay_t_0_0_1 + 32'sd1] = intdelay_reg_1[intdelay_t_0_0_1];
    end

  end

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg_2 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg_2[0] <= validIn;
          intdelay_reg_2[32'sd2:32'sd1] <= intdelay_reg_2[32'sd1:32'sd0];
        end
      end
    end

  assign din_1_vld_dly = intdelay_reg_2[2];

  RADIX22FFT_CTRL1_1 u_CTRL1_1_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld),
                                  .dinXTwdl_1_1_vld_1(dinXTwdl_1_1_vld),
                                  .rd_1_Addr(rd_1_Addr),  // ufix2
                                  .rd_1_Enb(rd_1_Enb),
                                  .proc_1_enb(proc_1_enb)
                                  );

  RADIX22FFT_SDF1_1 u_SDF1_1_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .din_1_1_re_dly(din_1_1_re_dly),  // sfix16
                                .din_1_1_im_dly(din_1_1_im_dly),  // sfix16
                                .din_1_vld_dly(din_1_vld_dly),
                                .rd_1_Addr(rd_1_Addr),  // ufix2
                                .rd_1_Enb(rd_1_Enb),
                                .proc_1_enb(proc_1_enb),
                                .dout_1_1_re(dout_1_1_re),  // sfix17
                                .dout_1_1_im(dout_1_1_im),  // sfix17
                                .dout_1_1_vld(dout_1_1_vld),
                                .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld)
                                );

  RADIX22FFT_CTRL1_2 u_CTRL2_2_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dout_1_1_vld(dout_1_1_vld),
                                  .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld),
                                  .rd_2_Addr(rd_2_Addr),  // ufix1
                                  .rd_2_Enb(rd_2_Enb),
                                  .proc_2_enb(proc_2_enb),
                                  .multiply_2_J(multiply_2_J)
                                  );

  RADIX22FFT_SDF2_2 u_SDF2_2_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .dout_1_1_re(dout_1_1_re),  // sfix17
                                .dout_1_1_im(dout_1_1_im),  // sfix17
                                .dout_1_1_vld(dout_1_1_vld),
                                .rd_2_Addr(rd_2_Addr),  // ufix1
                                .rd_2_Enb(rd_2_Enb),
                                .proc_2_enb(proc_2_enb),
                                .multiply_2_J(multiply_2_J),
                                .dout_2_1_re(dout_2_1_re),  // sfix18
                                .dout_2_1_im(dout_2_1_im),  // sfix18
                                .dout_2_1_vld(dout_2_1_vld),
                                .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld)
                                );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_2 = 32'sd0; intdelay_t_1_2 <= 32'sd2; intdelay_t_1_2 = intdelay_t_1_2 + 32'sd1) begin
          intdelay_reg_3[intdelay_t_1_2] <= 18'sb000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(intdelay_t_0_1_2 = 32'sd0; intdelay_t_0_1_2 <= 32'sd2; intdelay_t_0_1_2 = intdelay_t_0_1_2 + 32'sd1) begin
            intdelay_reg_3[intdelay_t_0_1_2] <= intdelay_reg_next_2[intdelay_t_0_1_2];
          end
        end
      end
    end

  always @* begin
    din_3_re_dly = intdelay_reg_3[2];
    intdelay_reg_next_2[0] = dout_2_1_re;

    for(intdelay_t_0_0_2 = 32'sd0; intdelay_t_0_0_2 <= 32'sd1; intdelay_t_0_0_2 = intdelay_t_0_0_2 + 32'sd1) begin
      intdelay_reg_next_2[intdelay_t_0_0_2 + 32'sd1] = intdelay_reg_3[intdelay_t_0_0_2];
    end

  end

  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_3 = 32'sd0; intdelay_t_1_3 <= 32'sd2; intdelay_t_1_3 = intdelay_t_1_3 + 32'sd1) begin
          intdelay_reg_4[intdelay_t_1_3] <= 18'sb000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(intdelay_t_0_1_3 = 32'sd0; intdelay_t_0_1_3 <= 32'sd2; intdelay_t_0_1_3 = intdelay_t_0_1_3 + 32'sd1) begin
            intdelay_reg_4[intdelay_t_0_1_3] <= intdelay_reg_next_3[intdelay_t_0_1_3];
          end
        end
      end
    end

  always @* begin
    din_3_im_dly = intdelay_reg_4[2];
    intdelay_reg_next_3[0] = dout_2_1_im;

    for(intdelay_t_0_0_3 = 32'sd0; intdelay_t_0_0_3 <= 32'sd1; intdelay_t_0_0_3 = intdelay_t_0_0_3 + 32'sd1) begin
      intdelay_reg_next_3[intdelay_t_0_0_3 + 32'sd1] = intdelay_reg_4[intdelay_t_0_0_3];
    end

  end

  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        intdelay_reg_5 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg_5[0] <= dout_2_1_vld;
          intdelay_reg_5[32'sd2:32'sd1] <= intdelay_reg_5[32'sd1:32'sd0];
        end
      end
    end

  assign din_3_vld_dly = intdelay_reg_5[2];

  TWDLROM_3_1 u_twdlROM_3 (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .dout_2_1_vld(dout_2_1_vld),
                           .twdl_3_re(twdl_3_re),  // sfix16_En14
                           .twdl_3_im(twdl_3_im)  // sfix16_En14
                           );

  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        rd_3_Enb_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          rd_3_Enb_dly <= rd_3_Enb;
        end
      end
    end

  RADIX22FFT_CTRL1_1_block u_CTRLRX2 (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .dinXTwdl_3_vld(dinXTwdl_3_vld),
                                      .dinXTwdl_3_vld_1(dinXTwdl_3_vld),
                                      .rd_3_Addr(rd_3_Addr),
                                      .rd_3_Enb(rd_3_Enb),
                                      .proc_3_enb(proc_3_enb)
                                      );

  RADIX22FFT_SDF1_3 u_RADIX2 (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .din_3_re_dly(din_3_re_dly),  // sfix18
                              .din_3_im_dly(din_3_im_dly),  // sfix18
                              .din_3_vld_dly(din_3_vld_dly),
                              .rd_3_Addr(rd_3_Addr),
                              .rd_3_Enb_dly(rd_3_Enb_dly),
                              .twdl_3_re(twdl_3_re),  // sfix16_En14
                              .twdl_3_im(twdl_3_im),  // sfix16_En14
                              .proc_3_enb(proc_3_enb),
                              .dout_3_re(dout_3_re),  // sfix19
                              .dout_3_im(dout_3_im),  // sfix19
                              .dout_3_vld(dout_3_vld),
                              .dinXTwdl_3_vld(dinXTwdl_3_vld)
                              );

  RADIX2FFT_bitNatural u_NaturalOrder_Stage (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_3_re(dout_3_re),  // sfix19
                                             .dout_3_im(dout_3_im),  // sfix19
                                             .dout_3_vld(dout_3_vld),
                                             .dout_re1(dout_re1),  // sfix19
                                             .dout_im1(dout_im1),  // sfix19
                                             .dout_vld1(dout_vld1)
                                             );

  assign dataOut_re = dout_re1;

  assign dataOut_im = dout_im1;

  assign validOut = dout_vld1;

endmodule  // FFT

