// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\fft8_dut_tb.v
// Created: 2026-07-16 10:55:51
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fft8_dut_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fft8_dut_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire rawData_validIn;
  wire validOut_done;  // ufix1
  wire rdEnb;
  wire validOut_done_enb;  // ufix1
  reg [7:0] dataOut_re_addr;  // ufix8
  wire validOut_lastAddr;  // ufix1
  wire resetn;
  reg  check2_done;  // ufix1
  wire dataOut_re_done;  // ufix1
  wire dataOut_re_done_enb;  // ufix1
  wire dataOut_re_active;  // ufix1
  reg  holdData_validIn;
  reg  validIn_offset;
  wire validIn_1;
  reg [7:0] dataIn_addr;  // ufix8
  wire dataIn_active;  // ufix1
  reg  tb_enb_delay;
  wire dataIn_enb;  // ufix1
  wire [7:0] dataIn_addr_delay_1;  // ufix8
  wire tb_enb;
  reg signed [31:0] fp_dataIn;  // sfix32
  wire snkDone;
  reg signed [15:0] rawData_dataIn;  // int16
  reg signed [31:0] status_dataIn;  // sfix32
  reg signed [15:0] holdData_dataIn;  // int16
  reg signed [15:0] dataIn_offset;  // int16
  wire signed [15:0] dataIn;  // int16
  wire snkDonen;
  wire ce_out;
  wire signed [18:0] dataOut_re;  // sfix19
  wire signed [18:0] dataOut_im;  // sfix19
  wire validOut;
  wire dataOut_re_enb;  // ufix1
  wire dataOut_re_lastAddr;  // ufix1
  reg  check1_done;  // ufix1
  wire [7:0] dataOut_re_addr_delay_1;  // ufix8
  reg signed [31:0] fp_dataOut_re_expected;  // sfix32
  reg signed [18:0] dataOut_re_expected;  // sfix19
  reg signed [31:0] status_dataOut_re_expected;  // sfix32
  wire signed [18:0] dataOut_re_ref;  // sfix19
  reg  dataOut_re_testFailure;  // ufix1
  wire signed [18:0] dataOut_im_expected_1;  // sfix19
  wire signed [18:0] dataOut_im_ref;  // sfix19
  reg  dataOut_im_testFailure;  // ufix1
  wire [7:0] validOut_addr_delay_1;  // ufix8
  reg signed [31:0] fp_validOut_expected;  // sfix32
  reg  validOut_expected;
  reg signed [31:0] status_validOut_expected;  // sfix32
  wire validOut_ref;
  reg  validOut_testFailure;  // ufix1
  wire testFailure;  // ufix1


  // Data source for validIn
  assign rawData_validIn = 1'b1;

  assign validOut_done_enb = validOut_done & rdEnb;

  assign validOut_lastAddr = dataOut_re_addr >= 8'b10010110;

  assign validOut_done = validOut_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_2
      if (reset) begin
        check2_done <= 0;
      end
      else begin
        if (validOut_done_enb) begin
          check2_done <= validOut_done;
        end
      end
    end

  assign dataOut_re_done_enb = dataOut_re_done & rdEnb;

  assign dataOut_re_active = dataOut_re_addr != 8'b10010110;

  // holdData reg for validIn
  always @(posedge clk or posedge reset)
    begin : stimuli_validIn
      if (reset) begin
        holdData_validIn <= 1'bx;
      end
      else begin
        holdData_validIn <= rawData_validIn;
      end
    end

  always @(rawData_validIn or rdEnb)
    begin : stimuli_validIn_1
      if (rdEnb == 1'b0) begin
        validIn_offset <= holdData_validIn;
      end
      else begin
        validIn_offset <= rawData_validIn;
      end
    end

  assign #2 validIn_1 = validIn_offset;

  assign dataIn_active = dataIn_addr != 8'b10010110;

  assign dataIn_enb = dataIn_active & (rdEnb & tb_enb_delay);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 150
  always @(posedge clk or posedge reset)
    begin : toFix_process
      if (reset == 1'b1) begin
        dataIn_addr <= 8'b00000000;
      end
      else begin
        if (dataIn_enb) begin
          if (dataIn_addr >= 8'b10010110) begin
            dataIn_addr <= 8'b00000000;
          end
          else begin
            dataIn_addr <= dataIn_addr + 8'b00000001;
          end
        end
      end
    end

  assign #1 dataIn_addr_delay_1 = dataIn_addr;

  // Data source for dataIn
  initial
    begin : dataIn_fileread
      fp_dataIn = $fopen("dataIn.dat", "r");
      status_dataIn = $rewind(fp_dataIn);
    end

  always @(dataIn_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_dataIn <= 16'bx;
        if (snkDone == 1) begin
          $fclose(fp_dataIn);
        end
      end
      else if (rdEnb == 1) begin
        status_dataIn = $fscanf(fp_dataIn, "%h", rawData_dataIn);
      end
    end

  // holdData reg for dataIn
  always @(posedge clk or posedge reset)
    begin : stimuli_dataIn
      if (reset) begin
        holdData_dataIn <= 16'bx;
      end
      else begin
        holdData_dataIn <= rawData_dataIn;
      end
    end

  always @(rawData_dataIn or rdEnb)
    begin : stimuli_dataIn_1
      if (rdEnb == 1'b0) begin
        dataIn_offset <= holdData_dataIn;
      end
      else begin
        dataIn_offset <= rawData_dataIn;
      end
    end

  assign #2 dataIn = dataIn_offset;

  assign snkDonen =  ~ snkDone;

  assign resetn =  ~ reset;

  assign tb_enb = resetn & snkDonen;

  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay_process
      if (reset == 1'b1) begin
        tb_enb_delay <= 1'b0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (snkDone == 1'b0 ? tb_enb_delay :
              1'b0);

  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  fft8_dut u_fft8_dut (.clk(clk),
                       .reset(reset),
                       .clk_enable(clk_enable),
                       .dataIn(dataIn),  // int16
                       .validIn(validIn_1),
                       .ce_out(ce_out),
                       .dataOut_re(dataOut_re),  // sfix19
                       .dataOut_im(dataOut_im),  // sfix19
                       .validOut(validOut)
                       );

  assign dataOut_re_enb = ce_out & dataOut_re_active;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 150
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        dataOut_re_addr <= 8'b00000000;
      end
      else begin
        if (dataOut_re_enb) begin
          if (dataOut_re_addr >= 8'b10010110) begin
            dataOut_re_addr <= 8'b00000000;
          end
          else begin
            dataOut_re_addr <= dataOut_re_addr + 8'b00000001;
          end
        end
      end
    end

  assign dataOut_re_lastAddr = dataOut_re_addr >= 8'b10010110;

  assign dataOut_re_done = dataOut_re_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (dataOut_re_done_enb) begin
          check1_done <= dataOut_re_done;
        end
      end
    end

  assign snkDone = check1_done & check2_done;

  assign #1 dataOut_re_addr_delay_1 = dataOut_re_addr;

  // Data source for dataOut_re_expected
  initial
    begin : dataOut_re_expected_fileread
      fp_dataOut_re_expected = $fopen("dataOut_re_expected.dat", "r");
      status_dataOut_re_expected = $rewind(fp_dataOut_re_expected);
    end

  always @(dataOut_re_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        dataOut_re_expected <= 19'bx;
        if (snkDone == 1) begin
          $fclose(fp_dataOut_re_expected);
        end
      end
      else if (ce_out == 1) begin
        status_dataOut_re_expected = $fscanf(fp_dataOut_re_expected, "%h", dataOut_re_expected);
      end
    end

  assign dataOut_re_ref = dataOut_re_expected;

  always @(posedge clk or posedge reset)
    begin : dataOut_re_checker
      if (reset == 1'b1) begin
        dataOut_re_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && dataOut_re !== dataOut_re_ref) begin
          dataOut_re_testFailure <= 1'b1;
          $display("ERROR in dataOut_re at time %t : Expected '%h' Actual '%h'", $time, dataOut_re_ref, dataOut_re);
        end
      end
    end

  // Data source for dataOut_im_expected
  assign dataOut_im_expected_1 = 19'sb0000000000000000000;

  assign dataOut_im_ref = dataOut_im_expected_1;

  always @(posedge clk or posedge reset)
    begin : dataOut_im_checker
      if (reset == 1'b1) begin
        dataOut_im_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && dataOut_im !== dataOut_im_ref) begin
          dataOut_im_testFailure <= 1'b1;
          $display("ERROR in dataOut_im at time %t : Expected '%h' Actual '%h'", $time, dataOut_im_ref, dataOut_im);
        end
      end
    end

  assign #1 validOut_addr_delay_1 = dataOut_re_addr;

  // Data source for validOut_expected
  initial
    begin : validOut_expected_fileread
      fp_validOut_expected = $fopen("validOut_expected.dat", "r");
      status_validOut_expected = $rewind(fp_validOut_expected);
    end

  always @(validOut_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        validOut_expected <= 1'bx;
        if (snkDone == 1) begin
          $fclose(fp_validOut_expected);
        end
      end
      else if (ce_out == 1) begin
        status_validOut_expected = $fscanf(fp_validOut_expected, "%h", validOut_expected);
      end
    end

  assign validOut_ref = validOut_expected;

  always @(posedge clk or posedge reset)
    begin : validOut_checker
      if (reset == 1'b1) begin
        validOut_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && validOut !== validOut_ref) begin
          validOut_testFailure <= 1'b1;
          $display("ERROR in validOut at time %t : Expected '%h' Actual '%h'", $time, validOut_ref, validOut);
        end
      end
    end

  assign testFailure = validOut_testFailure | (dataOut_re_testFailure | dataOut_im_testFailure);

  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // fft8_dut_tb

