// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\fft8_dut.v
// Created: 2026-07-16 10:54:42
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut_re                    ce_out        1
// dataOut_im                    ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fft8_dut
// Source Path: fft8/fft8_dut
// Hierarchy Level: 0
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fft8_dut
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // int16
  input   validIn;
  output  ce_out;
  output  signed [18:0] dataOut_re;  // sfix19
  output  signed [18:0] dataOut_im;  // sfix19
  output  validOut;


  wire signed [18:0] FFT_out1_re;  // sfix19
  wire signed [18:0] FFT_out1_im;  // sfix19
  wire FFT_out2;


  FFT u_FFT (.clk(clk),
             .reset(reset),
             .enb(clk_enable),
             .dataIn(dataIn),  // int16
             .validIn(validIn),
             .dataOut_re(FFT_out1_re),  // sfix19
             .dataOut_im(FFT_out1_im),  // sfix19
             .validOut(FFT_out2)
             );
  assign dataOut_re = FFT_out1_re;

  assign dataOut_im = FFT_out1_im;

  assign validOut = FFT_out2;

  assign ce_out = clk_enable;

endmodule  // fft8_dut

