exec xvlog -sv  SimpleDualPortRAM_generic.v
exec xvlog -sv  SDFCommutator1.v
exec xvlog -sv  RADIX22FFT_SDF1_1.v
exec xvlog -sv  RADIX22FFT_CTRL1_1.v
exec xvlog -sv  SDFCommutator2.v
exec xvlog -sv  RADIX22FFT_SDF2_2.v
exec xvlog -sv  RADIX22FFT_CTRL1_2.v
exec xvlog -sv  TWDLROM_3_1.v
exec xvlog -sv  Complex4Multiply.v
exec xvlog -sv  SDFCommutator3.v
exec xvlog -sv  RADIX22FFT_SDF1_3.v
exec xvlog -sv  RADIX22FFT_CTRL1_1_block.v
exec xvlog -sv  RADIX2FFT_bitNatural.v
exec xvlog -sv  FFT.v
exec xvlog -sv  fft8_dut.v
