// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\RADIX22FFT_CTRL1_1_block.v
// Created: 2026-07-16 10:54:42
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_CTRL1_1_block
// Source Path: fft8/fft8_dut/FFT/RADIX22FFT_CTRL1_1
// Hierarchy Level: 2
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_CTRL1_1_block
          (clk,
           reset,
           enb,
           dinXTwdl_3_vld,
           dinXTwdl_3_vld_1,
           rd_3_Addr,
           rd_3_Enb,
           proc_3_enb);


  input   clk;
  input   reset;
  input   enb;
  input   dinXTwdl_3_vld;
  input   dinXTwdl_3_vld_1;
  output  rd_3_Addr;
  output  rd_3_Enb;
  output  proc_3_enb;


  reg [1:0] SDFController_wrState;  // ufix2
  reg [1:0] SDFController_rdState;  // ufix2
  reg  SDFController_rdAddr_reg;  // ufix1
  reg [1:0] SDFController_multjState;  // ufix2
  reg [1:0] SDFController_wrState_next;  // ufix2
  reg [1:0] SDFController_rdState_next;  // ufix2
  reg  SDFController_rdAddr_reg_next;  // ufix1
  reg [1:0] SDFController_multjState_next;  // ufix2
  reg  rd_3_Addr_1;
  reg  rd_3_Enb_1;
  reg  proc_3_enb_1;
  reg  multiply_3_J;


  // SDFController
  always @(posedge clk or posedge reset)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_rdAddr_reg <= 1'b0;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
      end
      else begin
        if (enb) begin
          SDFController_wrState <= SDFController_wrState_next;
          SDFController_rdState <= SDFController_rdState_next;
          SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
          SDFController_multjState <= SDFController_multjState_next;
        end
      end
    end

  always @(SDFController_multjState, SDFController_rdAddr_reg, SDFController_rdState,
       SDFController_wrState, dinXTwdl_3_vld, dinXTwdl_3_vld_1) begin
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_multjState_next = SDFController_multjState;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_3_J = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          multiply_3_J = 1'b0;
          if (SDFController_rdState == 2'b00) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          multiply_3_J = 1'b0;
          SDFController_multjState_next = 2'b11;
        end
      2'b11 :
        begin
          multiply_3_J = 1'b1;
          SDFController_multjState_next = 2'b00;
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_3_J = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_3_Enb_1 = 1'b0;
          if ((SDFController_wrState == 2'b11) && dinXTwdl_3_vld) begin
            SDFController_rdState_next = 2'b01;
            rd_3_Enb_1 = dinXTwdl_3_vld_1;
          end
        end
      2'b01 :
        begin
          rd_3_Enb_1 = dinXTwdl_3_vld_1;
          if (dinXTwdl_3_vld_1) begin
            SDFController_rdState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_3_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          proc_3_enb_1 = 1'b0;
          if (dinXTwdl_3_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      2'b11 :
        begin
          SDFController_wrState_next = 2'b11;
          proc_3_enb_1 = 1'b0;
          if (dinXTwdl_3_vld) begin
            SDFController_wrState_next = 2'b10;
            proc_3_enb_1 = 1'b1;
          end
        end
      2'b10 :
        begin
          proc_3_enb_1 = 1'b0;
          SDFController_wrState_next = 2'b10;
          if (dinXTwdl_3_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          proc_3_enb_1 = 1'b0;
        end
    endcase
    rd_3_Addr_1 = SDFController_rdAddr_reg;
  end

  assign rd_3_Addr = rd_3_Addr_1;

  assign rd_3_Enb = rd_3_Enb_1;

  assign proc_3_enb = proc_3_enb_1;

endmodule  // RADIX22FFT_CTRL1_1_block

