// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\RADIX22FFT_SDF1_3.v
// Created: 2026-07-16 10:54:42
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_3
// Source Path: fft8/fft8_dut/FFT/RADIX22FFT_SDF1_3
// Hierarchy Level: 2
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_3
          (clk,
           reset,
           enb,
           din_3_re_dly,
           din_3_im_dly,
           din_3_vld_dly,
           rd_3_Addr,
           rd_3_Enb_dly,
           twdl_3_re,
           twdl_3_im,
           proc_3_enb,
           dout_3_re,
           dout_3_im,
           dout_3_vld,
           dinXTwdl_3_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] din_3_re_dly;  // sfix18
  input   signed [17:0] din_3_im_dly;  // sfix18
  input   din_3_vld_dly;
  input   rd_3_Addr;
  input   rd_3_Enb_dly;
  input   signed [15:0] twdl_3_re;  // sfix16_En14
  input   signed [15:0] twdl_3_im;  // sfix16_En14
  input   proc_3_enb;
  output  signed [18:0] dout_3_re;  // sfix19
  output  signed [18:0] dout_3_im;  // sfix19
  output  dout_3_vld;
  output  dinXTwdl_3_vld;


  wire signed [18:0] din_re;  // sfix19
  wire signed [18:0] din_im;  // sfix19
  wire signed [18:0] dinXTwdl_re;  // sfix19
  wire signed [18:0] dinXTwdl_im;  // sfix19
  reg  x_vld;
  wire signed [18:0] wrData_re;  // sfix19
  wire signed [18:0] wrData_im;  // sfix19
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [18:0] twoLocationReg_0_MEM_re_0;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_im_0;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_re_1;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_im_1;  // sfix19
  reg signed [18:0] twoLocationReg_0_dout_re_reg;  // sfix19
  reg signed [18:0] twoLocationReg_0_dout_im_reg;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_re_0_next;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_im_0_next;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_re_1_next;  // sfix19
  reg signed [18:0] twoLocationReg_0_MEM_im_1_next;  // sfix19
  reg signed [18:0] twoLocationReg_0_dout_re_reg_next;  // sfix19
  reg signed [18:0] twoLocationReg_0_dout_im_reg_next;  // sfix19
  reg signed [18:0] x_re;  // sfix19
  reg signed [18:0] x_im;  // sfix19
  reg signed [19:0] Radix22ButterflyG1_btf1_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf1_im_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_im_reg;  // sfix20
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix19
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [19:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_1;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_2;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_3;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_4;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_5;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_6;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_7;  // sfix20
  wire signed [19:0] Radix22ButterflyG1_8;  // sfix20
  reg signed [18:0] xf_re;  // sfix19
  reg signed [18:0] xf_im;  // sfix19
  reg  xf_vld;
  wire signed [18:0] dinXTwdlf_re;  // sfix19
  wire signed [18:0] dinXTwdlf_im;  // sfix19
  wire dinxTwdlf_vld;
  wire signed [18:0] btf1_re;  // sfix19
  wire signed [18:0] btf1_im;  // sfix19
  wire signed [18:0] btf2_re;  // sfix19
  wire signed [18:0] btf2_im;  // sfix19
  reg  btf_vld;


  assign din_re = {din_3_re_dly[17], din_3_re_dly};

  assign din_im = {din_3_im_dly[17], din_3_im_dly};

  Complex4Multiply u_MUL4 (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .din_re(din_re),  // sfix19
                           .din_im(din_im),  // sfix19
                           .din_3_vld_dly(din_3_vld_dly),
                           .twdl_3_re(twdl_3_re),  // sfix16_En14
                           .twdl_3_im(twdl_3_im),  // sfix16_En14
                           .dinXTwdl_re(dinXTwdl_re),  // sfix19
                           .dinXTwdl_im(dinXTwdl_im),  // sfix19
                           .dinXTwdl_3_vld(dinXTwdl_3_vld)
                           );

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_3_Enb_dly;
        end
      end
    end

  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 19'sb0000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 19'sb0000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 19'sb0000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 19'sb0000000000000000000;
        twoLocationReg_0_dout_re_reg <= 19'sb0000000000000000000;
        twoLocationReg_0_dout_im_reg <= 19'sb0000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_3_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_3_Addr) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end

  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 20'sb00000000000000000000;
        xf_re <= 19'sb0000000000000000000;
        xf_im <= 19'sb0000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          xf_re <= x_re;
          xf_im <= x_im;
          xf_vld <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb && dinXTwdl_3_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_3_enb) && dinXTwdl_3_vld;
  assign Radix22ButterflyG1_1 = {x_re[18], x_re};
  assign Radix22ButterflyG1_2 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_1 + Radix22ButterflyG1_2;
  assign Radix22ButterflyG1_3 = {x_re[18], x_re};
  assign Radix22ButterflyG1_4 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_3 - Radix22ButterflyG1_4;
  assign Radix22ButterflyG1_5 = {x_im[18], x_im};
  assign Radix22ButterflyG1_6 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_5 + Radix22ButterflyG1_6;
  assign Radix22ButterflyG1_7 = {x_im[18], x_im};
  assign Radix22ButterflyG1_8 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_7 - Radix22ButterflyG1_8;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[18:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[18:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[18:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[18:0];

  SDFCommutator3 u_SDFCOMMUTATOR_3 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_3_vld_dly(din_3_vld_dly),
                                    .xf_re(xf_re),  // sfix19
                                    .xf_im(xf_im),  // sfix19
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix19
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix19
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix19
                                    .btf1_im(btf1_im),  // sfix19
                                    .btf2_re(btf2_re),  // sfix19
                                    .btf2_im(btf2_im),  // sfix19
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix19
                                    .wrData_im(wrData_im),  // sfix19
                                    .wrAddr(wrAddr),  // ufix1
                                    .wrEnb(wrEnb),
                                    .dout_3_re(dout_3_re),  // sfix19
                                    .dout_3_im(dout_3_im),  // sfix19
                                    .dout_3_vld(dout_3_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_3

