// -------------------------------------------------------------
// 
// File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\RADIX22FFT_SDF2_2.v
// Created: 2026-07-16 10:54:42
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_2
// Source Path: fft8/fft8_dut/FFT/RADIX22FFT_SDF2_2
// Hierarchy Level: 2
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_2
          (clk,
           reset,
           enb,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           rd_2_Addr,
           rd_2_Enb,
           proc_2_enb,
           multiply_2_J,
           dout_2_1_re,
           dout_2_1_im,
           dout_2_1_vld,
           dinXTwdl_2_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] dout_1_1_re;  // sfix17
  input   signed [16:0] dout_1_1_im;  // sfix17
  input   dout_1_1_vld;
  input   rd_2_Addr;  // ufix1
  input   rd_2_Enb;
  input   proc_2_enb;
  input   multiply_2_J;
  output  signed [17:0] dout_2_1_re;  // sfix18
  output  signed [17:0] dout_2_1_im;  // sfix18
  output  dout_2_1_vld;
  output  dinXTwdl_2_1_vld;


  wire signed [17:0] din_re;  // sfix18
  wire signed [17:0] din_im;  // sfix18
  wire saveEnb;
  wire dinVld;
  reg signed [17:0] din_re_dly1;  // sfix18
  reg signed [17:0] btfin_re;  // sfix18
  reg signed [17:0] din_im_dly1;  // sfix18
  reg signed [17:0] btfin_im;  // sfix18
  wire mulIn_vld;
  reg  procEnb_dly1;
  reg  btfin_vld;
  reg  x_vld;
  reg  x_vld_dly;
  reg signed [17:0] x_im;  // sfix18
  reg signed [17:0] x_im_dly;  // sfix18
  wire signed [17:0] wrData_re;  // sfix18
  wire signed [17:0] wrData_im;  // sfix18
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [17:0] twoLocationReg_0_MEM_re_0;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_im_0;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_re_1;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_im_1;  // sfix18
  reg signed [17:0] twoLocationReg_0_dout_re_reg;  // sfix18
  reg signed [17:0] twoLocationReg_0_dout_im_reg;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_re_0_next;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_im_0_next;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_re_1_next;  // sfix18
  reg signed [17:0] twoLocationReg_0_MEM_im_1_next;  // sfix18
  reg signed [17:0] twoLocationReg_0_dout_re_reg_next;  // sfix18
  reg signed [17:0] twoLocationReg_0_dout_im_reg_next;  // sfix18
  reg signed [17:0] x_re;  // sfix18
  reg signed [17:0] x_re_dly;  // sfix18
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [18:0] Radix22ButterflyG2_btf1_re_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf1_im_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_re_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_im_reg;  // sfix19
  reg signed [17:0] Radix22ButterflyG2_din_re_dly;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_din_im_dly;  // sfix18
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [17:0] Radix22ButterflyG2_x_re_dly;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_x_im_dly;  // sfix18
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix18
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [18:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix19
  reg signed [17:0] Radix22ButterflyG2_din_re_dly_next;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_din_im_dly_next;  // sfix18
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [17:0] Radix22ButterflyG2_x_re_dly_next;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_x_im_dly_next;  // sfix18
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix18
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [17:0] xf_re;  // sfix18
  reg signed [17:0] xf_im;  // sfix18
  reg  xf_vld;
  reg signed [17:0] dinf_re;  // sfix18
  reg signed [17:0] dinf_im;  // sfix18
  reg  dinf_vld;
  reg signed [17:0] btf1_re;  // sfix18
  reg signed [17:0] btf1_im;  // sfix18
  reg signed [17:0] btf2_re;  // sfix18
  reg signed [17:0] btf2_im;  // sfix18
  reg  btfout_vld;
  reg signed [18:0] Radix22ButterflyG2_t_0_0;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_1;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_2_0;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_3;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_4_0;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_5;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_6_0;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_7;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_8_0;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_9;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_10;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_11;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_12;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_13;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_14;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_t_15;  // sfix19


  assign din_re = {dout_1_1_re[16], dout_1_1_re};

  assign din_im = {dout_1_1_im[16], dout_1_1_im};

  assign saveEnb =  ~ proc_2_enb;

  assign dinVld = dout_1_1_vld & saveEnb;

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_dly1 <= din_re;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_re <= din_re_dly1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_dly1 <= din_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_im <= din_im_dly1;
        end
      end
    end

  assign mulIn_vld = dout_1_1_vld & proc_2_enb;

  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          procEnb_dly1 <= mulIn_vld;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          btfin_vld <= procEnb_dly1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_2_Enb;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end

  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 18'sb000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 18'sb000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 18'sb000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 18'sb000000000000000000;
        twoLocationReg_0_dout_re_reg <= 18'sb000000000000000000;
        twoLocationReg_0_dout_im_reg <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_2_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_2_Addr == 1'b1) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end

  always @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end

  // Radix22ButterflyG2
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 18'sb000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_2_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_t_0_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_1 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_2_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_3 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_4_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_5 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_6_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_7 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_8_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_9 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_10 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_11 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_12 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_13 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_14 = 19'sb0000000000000000000;
    Radix22ButterflyG2_t_15 = 19'sb0000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_t_0_0 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_t_1 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_0_0 + Radix22ButterflyG2_t_1;
      Radix22ButterflyG2_t_2_0 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_t_3 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_2_0 - Radix22ButterflyG2_t_3;
      Radix22ButterflyG2_t_4_0 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_t_5 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_4_0 + Radix22ButterflyG2_t_5;
      Radix22ButterflyG2_t_6_0 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_t_7 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_6_0 - Radix22ButterflyG2_t_7;
    end
    else begin
      Radix22ButterflyG2_t_8_0 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_t_9 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_8_0 + Radix22ButterflyG2_t_9;
      Radix22ButterflyG2_t_10 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_t_11 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_10 - Radix22ButterflyG2_t_11;
      Radix22ButterflyG2_t_12 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_t_13 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_12 + Radix22ButterflyG2_t_13;
      Radix22ButterflyG2_t_14 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_t_15 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_14 - Radix22ButterflyG2_t_15;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_2_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[17:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[17:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[17:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[17:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end

  SDFCommutator2 u_SDFCOMMUTATOR_2 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dout_1_1_vld(dout_1_1_vld),
                                    .xf_re(xf_re),  // sfix18
                                    .xf_im(xf_im),  // sfix18
                                    .xf_vld(xf_vld),
                                    .dinf_re(dinf_re),  // sfix18
                                    .dinf_im(dinf_im),  // sfix18
                                    .dinf_vld(dinf_vld),
                                    .btf1_re(btf1_re),  // sfix18
                                    .btf1_im(btf1_im),  // sfix18
                                    .btf2_re(btf2_re),  // sfix18
                                    .btf2_im(btf2_im),  // sfix18
                                    .btfout_vld(btfout_vld),
                                    .wrData_re(wrData_re),  // sfix18
                                    .wrData_im(wrData_im),  // sfix18
                                    .wrAddr(wrAddr),  // ufix1
                                    .wrEnb(wrEnb),
                                    .dout_2_1_re(dout_2_1_re),  // sfix18
                                    .dout_2_1_im(dout_2_1_im),  // sfix18
                                    .dout_2_1_vld(dout_2_1_vld)
                                    );

  assign dinXTwdl_2_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_2

