-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\backend.vhd
-- Created: 2026-07-17 10:00:05
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: backend
-- Source Path: dsp_filter/dsp_filter_dut/backend
-- Hierarchy Level: 1
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY backend IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        xi                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        sw1                               :   IN    std_logic;
        led                               :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        rgb                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END backend;


ARCHITECTURE rtl OF backend IS

  -- Signals
  SIGNAL xi_signed                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL led_tmp                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL rgb_tmp                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL e                                : signed(31 DOWNTO 0);  -- int32
  SIGNAL e_next                           : signed(31 DOWNTO 0);  -- int32

BEGIN
  xi_signed <= signed(xi);

  backend_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      e <= to_signed(16#00000000#, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      e <= e_next;
    END IF;
  END PROCESS backend_1_process;

  backend_1_output : PROCESS (e, sw1, xi_signed)
    VARIABLE ax : signed(31 DOWNTO 0);
    VARIABLE b0 : std_logic;
    VARIABLE b1 : std_logic;
    VARIABLE b2 : std_logic;
    VARIABLE b3 : std_logic;
    VARIABLE temp : signed(31 DOWNTO 0);
    VARIABLE c : signed(31 DOWNTO 0);
    VARIABLE e_temp : signed(31 DOWNTO 0);
    VARIABLE t_0 : signed(32 DOWNTO 0);
    VARIABLE sub_temp : signed(32 DOWNTO 0);
    VARIABLE add_temp : signed(32 DOWNTO 0);
    VARIABLE add_cast : signed(31 DOWNTO 0);
    VARIABLE add_cast_0 : signed(1 DOWNTO 0);
    VARIABLE add_cast_1 : signed(33 DOWNTO 0);
    VARIABLE add_cast_2 : signed(31 DOWNTO 0);
    VARIABLE add_cast_3 : signed(1 DOWNTO 0);
    VARIABLE add_cast_4 : signed(33 DOWNTO 0);
    VARIABLE add_cast_5 : signed(31 DOWNTO 0);
    VARIABLE add_cast_6 : signed(1 DOWNTO 0);
    VARIABLE add_cast_7 : signed(33 DOWNTO 0);
    VARIABLE add_cast_8 : signed(31 DOWNTO 0);
    VARIABLE add_temp_0 : signed(31 DOWNTO 0);
  BEGIN
    t_0 := to_signed(0, 33);
    IF xi_signed < to_signed(16#00000000#, 32) THEN 
      t_0 :=  - (resize(xi_signed, 33));
      IF (t_0(32) = '0') AND (t_0(31) /= '0') THEN 
        ax := X"7FFFFFFF";
      ELSIF (t_0(32) = '1') AND (t_0(31) /= '1') THEN 
        ax := X"80000000";
      ELSE 
        ax := t_0(31 DOWNTO 0);
      END IF;
    ELSE 
      ax := xi_signed;
    END IF;
    sub_temp := resize(ax, 33) - resize(e, 33);
    IF (sub_temp(32) = '0') AND (sub_temp(31) /= '0') THEN 
      temp := X"7FFFFFFF";
    ELSIF (sub_temp(32) = '1') AND (sub_temp(31) /= '1') THEN 
      temp := X"80000000";
    ELSE 
      temp := sub_temp(31 DOWNTO 0);
    END IF;
    c := SHIFT_RIGHT(temp, 6);
    add_temp := resize(e, 33) + resize(c, 33);
    IF (add_temp(32) = '0') AND (add_temp(31) /= '0') THEN 
      e_temp := X"7FFFFFFF";
    ELSIF (add_temp(32) = '1') AND (add_temp(31) /= '1') THEN 
      e_temp := X"80000000";
    ELSE 
      e_temp := add_temp(31 DOWNTO 0);
    END IF;
    IF e_temp > to_signed(16#00000640#, 32) THEN 
      b0 := '1';
    ELSE 
      b0 := '0';
    END IF;
    IF e_temp > to_signed(16#00000DAC#, 32) THEN 
      b1 := '1';
    ELSE 
      b1 := '0';
    END IF;
    IF e_temp > to_signed(16#0000157C#, 32) THEN 
      b2 := '1';
    ELSE 
      b2 := '0';
    END IF;
    IF e_temp > to_signed(16#00001D4C#, 32) THEN 
      b3 := '1';
    ELSE 
      b3 := '0';
    END IF;
    IF sw1 = '1' THEN 
      rgb_tmp <= to_unsigned(16#04#, 8);
    ELSE 
      rgb_tmp <= to_unsigned(16#02#, 8);
    END IF;
    add_cast := '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & b0;
    add_cast_0 := '0' & b1;
    add_cast_1 := resize(add_cast_0 & '0', 34);
    add_cast_2 := add_cast_1(31 DOWNTO 0);
    add_cast_3 := '0' & b2;
    add_cast_4 := resize(add_cast_3 & '0' & '0', 34);
    add_cast_5 := add_cast_4(31 DOWNTO 0);
    add_cast_6 := '0' & b3;
    add_cast_7 := resize(add_cast_6 & '0' & '0' & '0', 34);
    add_cast_8 := add_cast_7(31 DOWNTO 0);
    add_temp_0 := ((add_cast + add_cast_2) + add_cast_5) + add_cast_8;
    led_tmp <= unsigned(add_temp_0(7 DOWNTO 0));
    e_next <= e_temp;
  END PROCESS backend_1_output;


  led <= std_logic_vector(led_tmp);

  rgb <= std_logic_vector(rgb_tmp);

END rtl;

