-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\dsp_filter_dut.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 24
-- Target subsystem base rate: 24
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dsp_filter_dut
-- Source Path: dsp_filter/dsp_filter_dut
-- Hierarchy Level: 0
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dsp_filter_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        sw2                               :   IN    std_logic;
        sw1                               :   IN    std_logic;
        sw0                               :   IN    std_logic;
        led                               :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        rgb                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
        );
END dsp_filter_dut;


ARCHITECTURE rtl OF dsp_filter_dut IS

  -- Component Declarations
  COMPONENT NCO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          inc                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          sine                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT noise_gen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  COMPONENT FIR_LP
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
          );
  END COMPONENT;

  COMPONENT FIR_HP
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
          );
  END COMPONENT;

  COMPONENT backend
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          xi                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          sw1                             :   IN    std_logic;
          led                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          rgb                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : NCO
    USE ENTITY work.NCO(rtl);

  FOR ALL : noise_gen
    USE ENTITY work.noise_gen(rtl);

  FOR ALL : FIR_LP
    USE ENTITY work.FIR_LP(rtl);

  FOR ALL : FIR_HP
    USE ENTITY work.FIR_HP(rtl);

  FOR ALL : backend
    USE ENTITY work.backend(rtl);

  -- Signals
  SIGNAL incL_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL incH_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL inc_sel_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL valid_out1                       : std_logic;
  SIGNAL NCO_out1                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_out2                         : std_logic;
  SIGNAL NCO_out1_signed                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL zero_out1                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL y                                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL y_signed                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL noise_q14_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL noise_gate_out1                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL mix_out1                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL FIR_LP_out1                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL FIR_LP_out1_signed               : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL FIR_HP_out1                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL FIR_HP_out1_signed               : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL filt_sel_out1                    : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL filt_si_out1                     : signed(31 DOWNTO 0);  -- int32
  SIGNAL led_1                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL rgb_1                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL led_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL led_conv_out1                    : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL rgb_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL rgb_conv_out1                    : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  u_NCO : NCO
    PORT MAP( clk => clk,
              reset => reset,
              inc => std_logic_vector(inc_sel_out1),  -- int16
              validIn => valid_out1,
              sine => NCO_out1,  -- sfix16_En14
              validOut => NCO_out2
              );

  u_noise_gen : noise_gen
    PORT MAP( clk => clk,
              reset => reset,
              y => y  -- int16
              );

  u_FIR_LP : FIR_LP
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => std_logic_vector(mix_out1),  -- sfix16_En14
              validIn => NCO_out2,
              dataOut => FIR_LP_out1  -- sfix18_En14
              );

  u_FIR_HP : FIR_HP
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => std_logic_vector(mix_out1),  -- sfix16_En14
              validIn => NCO_out2,
              dataOut => FIR_HP_out1  -- sfix18_En14
              );

  u_backend : backend
    PORT MAP( clk => clk,
              reset => reset,
              xi => std_logic_vector(filt_si_out1),  -- int32
              sw1 => sw1,
              led => led_1,  -- uint8
              rgb => rgb_1  -- uint8
              );

  incL_out1 <= to_signed(16#0CCD#, 16);

  incH_out1 <= to_signed(16#4000#, 16);

  
  inc_sel_out1 <= incL_out1 WHEN sw2 = '0' ELSE
      incH_out1;

  valid_out1 <= '1';

  NCO_out1_signed <= signed(NCO_out1);

  zero_out1 <= to_signed(16#0000#, 16);

  y_signed <= signed(y);

  noise_q14_out1 <= y_signed;

  
  noise_gate_out1 <= zero_out1 WHEN sw0 = '0' ELSE
      noise_q14_out1;

  mix_out1 <= NCO_out1_signed + noise_gate_out1;

  FIR_LP_out1_signed <= signed(FIR_LP_out1);

  FIR_HP_out1_signed <= signed(FIR_HP_out1);

  
  filt_sel_out1 <= FIR_LP_out1_signed WHEN sw1 = '0' ELSE
      FIR_HP_out1_signed;

  filt_si_out1 <= resize(filt_sel_out1, 32);

  led_unsigned <= unsigned(led_1);

  led_conv_out1 <= led_unsigned(3 DOWNTO 0);

  led <= std_logic_vector(led_conv_out1);

  rgb_unsigned <= unsigned(rgb_1);

  rgb_conv_out1 <= rgb_unsigned(2 DOWNTO 0);

  rgb <= std_logic_vector(rgb_conv_out1);

END rtl;

