-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\Filter.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filter
-- Source Path: dsp_filter/dsp_filter_dut/FIR_HP/Filter
-- Hierarchy Level: 2
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dsp_filter_dut_pkg.ALL;

ENTITY Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
        );
END Filter;


ARCHITECTURE rtl OF Filter IS

  -- Component Declarations
  COMPONENT FilterCoef
    PORT( CoefOut                         :   OUT   vector_of_std_logic_vector16(0 TO 16)  -- sfix16_En15 [17]
          );
  END COMPONENT;

  COMPONENT subFilter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          coefIn                          :   IN    vector_of_std_logic_vector16(0 TO 16);  -- sfix16_En15 [17]
          dinRegVld                       :   IN    std_logic;
          dout_1_re                       :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterCoef
    USE ENTITY work.FilterCoef(rtl);

  FOR ALL : subFilter
    USE ENTITY work.subFilter(rtl);

  -- Signals
  SIGNAL dinRegVld                        : std_logic;
  SIGNAL dataIn_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinReg_0_re                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinReg2_0_re                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL CoefOut                          : vector_of_std_logic_vector16(0 TO 16);  -- ufix16 [17]
  SIGNAL dinReg2Vld                       : std_logic;
  SIGNAL dout_1_re                        : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_CoefTable_1 : FilterCoef
    PORT MAP( CoefOut => CoefOut  -- sfix16_En15 [17]
              );

  u_subFilter_1_re : subFilter
    PORT MAP( clk => clk,
              reset => reset,
              dinReg2_0_re => std_logic_vector(dinReg2_0_re),  -- sfix16_En14
              coefIn => CoefOut,  -- sfix16_En15 [17]
              dinRegVld => dinReg2Vld,
              dout_1_re => dout_1_re  -- sfix18_En14
              );

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinRegVld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      dinRegVld <= validIn;
    END IF;
  END PROCESS intdelay_process;


  dataIn_signed <= signed(dataIn);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg_0_re <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF validIn = '1' THEN
        dinReg_0_re <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg2_0_re <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF dinRegVld = '1' THEN
        dinReg2_0_re <= dinReg_0_re;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg2Vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      dinReg2Vld <= dinRegVld;
    END IF;
  END PROCESS intdelay_3_process;


  dataOut <= dout_1_re;

END rtl;

