-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\FilterTapSystolicWvldInC0_block.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterTapSystolicWvldInC0_block
-- Source Path: dsp_filter/dsp_filter_dut/FIR_LP/Filter/subFilter/FilterTapSystolicWvldInC0
-- Hierarchy Level: 4
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FilterTapSystolicWvldInC0_block IS
  PORT( clk                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En31
        dinRegVld                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En31
        );
END FilterTapSystolicWvldInC0_block;


ARCHITECTURE rtl OF FilterTapSystolicWvldInC0_block IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL fTap_din1_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_din1_reg2                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_din1_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_din1_reg2_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL dinDly2_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48_En31

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  addin_signed <= signed(addin);

  -- FilterTapSystolicWvldInC0
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      fTap_din1_reg1 <= fTap_din1_reg1_next;
      fTap_din1_reg2 <= fTap_din1_reg2_next;
      fTap_addout_reg <= fTap_addout_reg_next;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, dinReg2_0_re_signed, dinRegVld, fTap_addout_reg, fTap_din1_reg1,
       fTap_din1_reg2)
  BEGIN
    fTap_din1_reg1_next <= fTap_din1_reg1;
    fTap_din1_reg2_next <= fTap_din1_reg2;
    fTap_addout_reg_next <= fTap_addout_reg;
    IF dinRegVld = '1' THEN 
      fTap_addout_reg_next <= addin_signed;
    END IF;
    IF dinRegVld = '1' THEN 
      fTap_din1_reg2_next <= fTap_din1_reg1;
      fTap_din1_reg1_next <= dinReg2_0_re_signed;
    END IF;
    dinDly2_tmp <= fTap_din1_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

