-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\FilterTapSystolicPreAddWvlIn_block.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterTapSystolicPreAddWvlIn_block
-- Source Path: dsp_filter/dsp_filter_dut/FIR_LP/Filter/subFilter/FilterTapSystolicPreAddWvlIn
-- Hierarchy Level: 4
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dsp_filter_dut_pkg.ALL;

ENTITY FilterTapSystolicPreAddWvlIn_block IS
  PORT( clk                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dinPreAdd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        coefIn_0                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En17
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En31
        dinRegVld                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En31
        );
END FilterTapSystolicPreAddWvlIn_block;


ARCHITECTURE rtl OF FilterTapSystolicPreAddWvlIn_block IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinPreAdd_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL coefIn_0_signed                  : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL fTap_mult_reg                    : signed(32 DOWNTO 0) := to_signed(0, 33);  -- sfix33
  SIGNAL fTap_din1_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_din1_reg2                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_din2_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_preAdd_reg                  : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_coef_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_coef_reg2                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_mult_reg_next               : signed(32 DOWNTO 0);  -- sfix33_En31
  SIGNAL fTap_din1_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_din1_reg2_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_din2_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_preAdd_reg_next             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL fTap_coef_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL fTap_coef_reg2_next              : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL dinDly2_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48_En31

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  dinPreAdd_signed <= signed(dinPreAdd);

  coefIn_0_signed <= signed(coefIn_0);

  addin_signed <= signed(addin);

  -- FilterTapSystolicPreAddWvldIn
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      fTap_mult_reg <= fTap_mult_reg_next;
      fTap_din1_reg1 <= fTap_din1_reg1_next;
      fTap_din1_reg2 <= fTap_din1_reg2_next;
      fTap_din2_reg1 <= fTap_din2_reg1_next;
      fTap_preAdd_reg <= fTap_preAdd_reg_next;
      fTap_addout_reg <= fTap_addout_reg_next;
      fTap_coef_reg1 <= fTap_coef_reg1_next;
      fTap_coef_reg2 <= fTap_coef_reg2_next;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_0_signed, dinPreAdd_signed, dinReg2_0_re_signed,
       dinRegVld, fTap_addout_reg, fTap_coef_reg1, fTap_coef_reg2,
       fTap_din1_reg1, fTap_din1_reg2, fTap_din2_reg1, fTap_mult_reg,
       fTap_preAdd_reg)
    VARIABLE add_cast : signed(47 DOWNTO 0);
    VARIABLE add_cast_0 : signed(16 DOWNTO 0);
    VARIABLE add_cast_1 : signed(16 DOWNTO 0);
  BEGIN
    add_cast := to_signed(0, 48);
    add_cast_0 := to_signed(16#00000#, 17);
    add_cast_1 := to_signed(16#00000#, 17);
    fTap_mult_reg_next <= fTap_mult_reg;
    fTap_din1_reg1_next <= fTap_din1_reg1;
    fTap_din1_reg2_next <= fTap_din1_reg2;
    fTap_din2_reg1_next <= fTap_din2_reg1;
    fTap_preAdd_reg_next <= fTap_preAdd_reg;
    fTap_addout_reg_next <= fTap_addout_reg;
    fTap_coef_reg1_next <= fTap_coef_reg1;
    fTap_coef_reg2_next <= fTap_coef_reg2;
    IF dinRegVld = '1' THEN 
      add_cast := resize(fTap_mult_reg, 48);
      fTap_addout_reg_next <= add_cast + addin_signed;
      fTap_mult_reg_next <= fTap_preAdd_reg * fTap_coef_reg2;
      add_cast_0 := resize(fTap_din1_reg2, 17);
      add_cast_1 := resize(fTap_din2_reg1, 17);
      fTap_preAdd_reg_next <= add_cast_0 + add_cast_1;
      fTap_din1_reg2_next <= fTap_din1_reg1;
      fTap_din1_reg1_next <= dinReg2_0_re_signed;
      fTap_din2_reg1_next <= dinPreAdd_signed;
      fTap_coef_reg2_next <= fTap_coef_reg1;
      fTap_coef_reg1_next <= coefIn_0_signed;
    END IF;
    dinDly2_tmp <= fTap_din1_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

