-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\FIR_HP.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FIR_HP
-- Source Path: dsp_filter/dsp_filter_dut/FIR_HP
-- Hierarchy Level: 1
-- Model version: 1.11
-- 
-- Discrete FIR Filter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FIR_HP IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
        );
END FIR_HP;


ARCHITECTURE rtl OF FIR_HP IS

  -- Component Declarations
  COMPONENT Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Filter
    USE ENTITY work.Filter(rtl);

  -- Signals
  SIGNAL dataOut_tmp                      : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_FilterBank : Filter
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => dataIn,  -- sfix16_En14
              validIn => validIn,
              dataOut => dataOut_tmp  -- sfix18_En14
              );

  dataOut <= dataOut_tmp;

END rtl;

