-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\NCO.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NCO
-- Source Path: dsp_filter/dsp_filter_dut/NCO
-- Hierarchy Level: 1
-- Model version: 1.11
-- 
-- NCO
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY NCO IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        inc                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        validIn                           :   IN    std_logic;
        sine                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END NCO;


ARCHITECTURE rtl OF NCO IS

  -- Component Declarations
  COMPONENT DitherGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          validIn                         :   IN    std_logic;
          dither                          :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT WaveformGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          phaseIdx                        :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12_E4
          sine                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DitherGen
    USE ENTITY work.DitherGen(rtl);

  FOR ALL : WaveformGen
    USE ENTITY work.WaveformGen(rtl);

  -- Signals
  SIGNAL outsel_reg_reg                   : std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
  SIGNAL outsel                           : std_logic;
  SIGNAL outzero                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL const0                           : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL inc_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL pInc                             : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL validPInc                        : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accphase_reg                     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL addpInc                          : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL pOffset                          : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accoffset                        : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accoffsete_reg                   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dither                           : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL dither_unsigned                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL casteddither                     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dither_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accumulator                      : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accQuantized                     : unsigned(11 DOWNTO 0);  -- ufix12_E4
  SIGNAL outs                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL outs_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL validouts                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL sine_tmp                         : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_dither_inst : DitherGen
    PORT MAP( clk => clk,
              reset => reset,
              validIn => validIn,
              dither => dither  -- ufix4
              );

  u_Wave_inst : WaveformGen
    PORT MAP( clk => clk,
              reset => reset,
              phaseIdx => std_logic_vector(accQuantized),  -- ufix12_E4
              sine => outs  -- sfix16_En14
              );

  outsel_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      outsel_reg_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      outsel_reg_reg(0) <= validIn;
      outsel_reg_reg(4 DOWNTO 1) <= outsel_reg_reg(3 DOWNTO 0);
    END IF;
  END PROCESS outsel_reg_process;

  outsel <= outsel_reg_reg(4);

  outzero <= to_signed(16#0000#, 16);

  -- Constant Zero
  const0 <= to_signed(16#0000#, 16);

  inc_signed <= signed(inc);

  pInc <= inc_signed;

  
  validPInc <= const0 WHEN validIn = '0' ELSE
      pInc;

  -- Add phase increment
  addpInc <= accphase_reg + validPInc;

  -- Phase increment accumulator register
  AccPhaseRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accphase_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      accphase_reg <= addpInc;
    END IF;
  END PROCESS AccPhaseRegister_process;


  pOffset <= to_signed(16#0000#, 16);

  -- Add phase offset
  accoffset <= accphase_reg + pOffset;

  -- Phase offset accumulator register
  AccOffsetRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accoffsete_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      accoffsete_reg <= accoffset;
    END IF;
  END PROCESS AccOffsetRegister_process;


  dither_unsigned <= unsigned(dither);

  casteddither <= signed(resize(dither_unsigned, 16));

  -- Dither input register
  DitherRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dither_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      dither_reg <= casteddither;
    END IF;
  END PROCESS DitherRegister_process;


  -- Add dither
  accumulator <= accoffsete_reg + dither_reg;

  -- Phase quantization
  accQuantized <= unsigned(accumulator(15 DOWNTO 4));

  outs_signed <= signed(outs);

  
  validouts <= outzero WHEN outsel = '0' ELSE
      outs_signed;

  -- Output register
  OutputRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sine_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      sine_tmp <= validouts;
    END IF;
  END PROCESS OutputRegister_process;


  sine <= std_logic_vector(sine_tmp);

  -- validOut register
  validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      validOut <= outsel;
    END IF;
  END PROCESS validOut_reg_process;


END rtl;

