-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\noise_gen.vhd
-- Created: 2026-07-17 10:00:05
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: noise_gen
-- Source Path: dsp_filter/dsp_filter_dut/noise_gen
-- Hierarchy Level: 1
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY noise_gen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END noise_gen;


ARCHITECTURE rtl OF noise_gen IS

  -- Signals
  SIGNAL y_tmp                            : signed(15 DOWNTO 0);  -- int16
  SIGNAL state                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL state_next                       : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  noise_gen_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      state <= to_unsigned(16#ACE1#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      state <= state_next;
    END IF;
  END PROCESS noise_gen_1_process;

  noise_gen_1_output : PROCESS (state)
    VARIABLE lsb : unsigned(15 DOWNTO 0);
    VARIABLE hi : signed(15 DOWNTO 0);
    VARIABLE state_temp : unsigned(15 DOWNTO 0);
    VARIABLE cast : signed(31 DOWNTO 0);
    VARIABLE cast_0 : signed(31 DOWNTO 0);
    VARIABLE cast_1 : signed(31 DOWNTO 0);
    VARIABLE cast_2 : signed(31 DOWNTO 0);
    VARIABLE cast_3 : signed(31 DOWNTO 0);
    VARIABLE cast_4 : signed(31 DOWNTO 0);
    VARIABLE cast_5 : signed(31 DOWNTO 0);
    VARIABLE cast_6 : signed(31 DOWNTO 0);
    VARIABLE sub_cast : signed(47 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(31 DOWNTO 0);
    VARIABLE sub_temp : signed(31 DOWNTO 0);
  BEGIN
    cast_4 := to_signed(16#00000000#, 32);
    cast_3 := to_signed(16#00000000#, 32);
    cast := signed(resize(state, 32));
    cast_0 := cast AND to_signed(16#00000001#, 32);
    lsb := unsigned(cast_0(15 DOWNTO 0));
    cast_1 := signed(resize(state, 32));
    cast_2 := SHIFT_RIGHT(cast_1, 1);
    state_temp := unsigned(cast_2(15 DOWNTO 0));
    IF lsb = to_unsigned(16#0001#, 16) THEN 
      cast_3 := signed(resize(state_temp, 32));
      cast_4 := cast_3 XOR to_signed(16#0000B400#, 32);
      state_temp := unsigned(cast_4(15 DOWNTO 0));
    END IF;
    cast_5 := signed(resize(state_temp, 32));
    cast_6 := SHIFT_RIGHT(cast_5, 8);
    hi := cast_6(15 DOWNTO 0);
    sub_cast := resize(hi & '0' & '0' & '0' & '0' & '0' & '0', 48);
    sub_cast_0 := sub_cast(31 DOWNTO 0);
    sub_temp := sub_cast_0 - 8192;
    y_tmp <= sub_temp(15 DOWNTO 0);
    state_next <= state_temp;
  END PROCESS noise_gen_1_output;


  y <= std_logic_vector(y_tmp);

END rtl;

