-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\dsp_hdl\hdlsrc\dsp_filter\subFilter.vhd
-- Created: 2026-07-17 10:00:06
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter
-- Source Path: dsp_filter/dsp_filter_dut/FIR_HP/Filter/subFilter
-- Hierarchy Level: 3
-- Model version: 1.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dsp_filter_dut_pkg.ALL;

ENTITY subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 16);  -- sfix16_En15 [17]
        dinRegVld                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En14
        );
END subFilter;


ARCHITECTURE rtl OF subFilter IS

  -- Component Declarations
  COMPONENT FilterTapSystolicPreAddWvlIn
    PORT( clk                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dinPreAdd                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En29
          dinRegVld                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En29
          );
  END COMPONENT;

  COMPONENT FilterTapSystolicWvldInC0
    PORT( clk                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En29
          dinRegVld                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En29
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicPreAddWvlIn
    USE ENTITY work.FilterTapSystolicPreAddWvlIn(rtl);

  FOR ALL : FilterTapSystolicWvldInC0
    USE ENTITY work.FilterTapSystolicWvldInC0(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(12 DOWNTO 0);  -- ufix1 [13]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En29
  SIGNAL dinPreAdd                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dinDly2_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_6                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_7                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL ZERO                             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL ZERO_OUT                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL dinDly2deadOut                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En29
  SIGNAL dout_cast                        : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL muxOut                           : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL dout_1_re_tmp                    : signed(17 DOWNTO 0);  -- sfix18_En14

BEGIN
  u_FilterTap_1 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(0),  -- sfix16_En15
              addin => std_logic_vector(addin),  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_1,  -- sfix16_En14
              tapout => tapout  -- sfix48_En29
              );

  u_FilterTap_2 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_1,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(1),  -- sfix16_En15
              addin => tapout,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_2,  -- sfix16_En14
              tapout => tapout_1  -- sfix48_En29
              );

  u_FilterTap_3 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_2,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(2),  -- sfix16_En15
              addin => tapout_1,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_3,  -- sfix16_En14
              tapout => tapout_2  -- sfix48_En29
              );

  u_FilterTap_4 : FilterTapSystolicWvldInC0
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_3,  -- sfix16_En14
              addin => tapout_2,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_4,  -- sfix16_En14
              tapout => tapout_3  -- sfix48_En29
              );

  u_FilterTap_5 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_4,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(4),  -- sfix16_En15
              addin => tapout_3,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_5,  -- sfix16_En14
              tapout => tapout_4  -- sfix48_En29
              );

  u_FilterTap_6 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_5,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(5),  -- sfix16_En15
              addin => tapout_4,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_6,  -- sfix16_En14
              tapout => tapout_5  -- sfix48_En29
              );

  u_FilterTap_7 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_6,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(6),  -- sfix16_En15
              addin => tapout_5,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2_7,  -- sfix16_En14
              tapout => tapout_6  -- sfix48_En29
              );

  u_FilterTap_8 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2_7,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(7),  -- sfix16_En15
              addin => tapout_6,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2,  -- sfix16_En14
              tapout => tapout_7  -- sfix48_En29
              );

  u_FilterTap_9 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              dinReg2_0_re => dinDly2,  -- sfix16_En14
              dinPreAdd => std_logic_vector(ZERO),  -- sfix16_En14
              coefIn_0 => coefIn(8),  -- sfix16_En15
              addin => tapout_7,  -- sfix48_En29
              dinRegVld => dinRegVld,
              dinDly2 => dinDly2deadOut,  -- sfix16_En14
              tapout => tapout_8  -- sfix48_En29
              );

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF dinRegVld = '1' THEN
        intdelay_reg(0) <= dinRegVld;
        intdelay_reg(12 DOWNTO 1) <= intdelay_reg(11 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(12);

  vldOutTmp <= dinRegVld AND vldShift;

  addin <= to_signed(0, 48);

  dinDly2_signed <= signed(dinDly2);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinPreAdd <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF dinRegVld = '1' THEN
        dinPreAdd <= dinDly2_signed;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  ZERO <= to_signed(16#0000#, 16);

  ZERO_OUT <= to_signed(16#00000#, 18);

  tapout_signed <= signed(tapout_8);

  dout_cast <= tapout_signed(32 DOWNTO 15);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dout_1_re_tmp <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      dout_1_re_tmp <= muxOut;
    END IF;
  END PROCESS intdelay_2_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

END rtl;

